version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.21
    commands:
      - echo "Installing dependencies..."
      - cd go-employee-api
      - go mod tidy
  build:
    commands:
      - echo "Building Lambda binary..."
      - GOOS=linux GOARCH=amd64 go build -o bootstrap main.go
      - zip function.zip bootstrap
  post_build:
    commands:
      - echo "Uploading Lambda function to AWS..."
      - aws lambda update-function-code --function-name Rishikesh-Employee-Lambda --zip-file fileb://function.zip
